# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Documents and Settings/cpusey/My Documents/Development/Python/ddPak/User Interface Files/ScannerInterface.ui'
#
# Created: Wed Oct 31 13:22:37 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1433, 899)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Resources/path2829.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    font: 87 8pt \"Arial Black\";\n"
"    background-color: rgb(255, 0, 0);\n"
"background-image: url(:/newPrefix/Resources/dinpattern-stripe.gif);\n"
"}\n"
"\n"
"#label,#label_8,#label_2,QRadioButton{color:#f26522;}\n"
"#lcdNumber{\n"
"    color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 0);}\n"
"#label_3,#label_4,#label_5,#label_6,#label_9,#label_16,#label_18,#label_21,#label_26,#label_23,#label_24{color:#f26522;font: 75 10pt \"Arial\";font-size:16px;}\n"
"#label_12,#label_13,#label_14,#label_15,#label_17,#label_19,#label_20,#label_22{color: rgb(255, 170, 0);font: 75 10pt \"Arial Black\";font-size:16px;}\n"
"\n"
"#label_7{\n"
"    \n"
"    \n"
"    font: 48pt \"Trebuchet MS\";\n"
"    \n"
"    \n"
"    color: rgb(170, 0, 255);\n"
"    }\n"
"\n"
"#centralwidget{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.057, y2:0.0681818, stop:0 rgba(81, 81, 81, 151), stop:0.98 rgba(0, 0, 0, 255));\n"
"\n"
"}\n"
"#label_10{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"    \n"
"    font: 75 48pt \"Glass Gauge\";\n"
"\n"
"}\n"
"QPushButton{\n"
"    \n"
"    \n"
"font: 75 8pt \"Arial Black\";\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888);\n"
"min-width: 80px;\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb);\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}\n"
"#label_11{\n"
"\n"
"    background-color: rgb(255, 170, 127);\n"
"\n"
"}\n"
"#highlabel,#goodlabel,#lowlabel{\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"    background-color: rgb(179, 179, 179);\n"
"font: 70 7pt \"Arial Black\";\n"
"\n"
"\n"
"}\n"
"\n"
"#tableView  {\n"
"gridline-color:  rgb(170, 85, 255);\n"
"\n"
"}\n"
"#pushButton_9,#pushButton_10,#pushButton_11,#pushButton_12{\n"
"min-width: 40px;\n"
"max-width: 40px;\n"
"min-height: 32px;\n"
"max-height: 32px;\n"
"height: 32px;\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("None")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Resources/path2829.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(48)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(91, 24))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        spacerItem3 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(301, 24))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(61, 24))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setMinimumSize(QtCore.QSize(61, 24))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(81, 24))
        self.label_15.setText("")
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        spacerItem6 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setMinimumSize(QtCore.QSize(41, 24))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        spacerItem7 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_3.addWidget(self.tableView_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_15.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_15.addWidget(self.radioButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_12.addWidget(self.pushButton_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 1, 0, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 2, 1)
        spacerItem10 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem12 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(221, 87))
        self.label_10.setBaseSize(QtCore.QSize(0, 0))
        self.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.highlabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highlabel.sizePolicy().hasHeightForWidth())
        self.highlabel.setSizePolicy(sizePolicy)
        self.highlabel.setMinimumSize(QtCore.QSize(31, 31))
        self.highlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.highlabel.setObjectName("highlabel")
        self.verticalLayout_4.addWidget(self.highlabel)
        self.goodlabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goodlabel.sizePolicy().hasHeightForWidth())
        self.goodlabel.setSizePolicy(sizePolicy)
        self.goodlabel.setMinimumSize(QtCore.QSize(31, 31))
        self.goodlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goodlabel.setObjectName("goodlabel")
        self.verticalLayout_4.addWidget(self.goodlabel)
        self.lowlabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowlabel.sizePolicy().hasHeightForWidth())
        self.lowlabel.setSizePolicy(sizePolicy)
        self.lowlabel.setMinimumSize(QtCore.QSize(31, 31))
        self.lowlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowlabel.setObjectName("lowlabel")
        self.verticalLayout_4.addWidget(self.lowlabel)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setMinimumSize(QtCore.QSize(71, 24))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(94, 29))
        self.pushButton.setIconSize(QtCore.QSize(128, 64))
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(94, 29))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(94, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(94, 29))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(94, 29))
        self.pushButton_6.setBaseSize(QtCore.QSize(136, 29))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        spacerItem14 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(94, 29))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.axWidget = QAxContainer.QAxWidget(self.scrollAreaWidgetContents)
        self.axWidget.setProperty("geometry", QtCore.QRect(10, 10, 581, 841))
        self.axWidget.setObjectName("axWidget")
        self.verticalLayout_6.addWidget(self.axWidget)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(54, 46))
        self.pushButton_9.setMaximumSize(QtCore.QSize(54, 46))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_13.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(54, 46))
        self.pushButton_10.setMaximumSize(QtCore.QSize(54, 46))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_13.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(54, 46))
        self.pushButton_11.setMaximumSize(QtCore.QSize(54, 46))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_13.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(54, 46))
        self.pushButton_12.setMaximumSize(QtCore.QSize(54, 46))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_13.addWidget(self.pushButton_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 3, 2, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 259, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1433, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEDit = QtWidgets.QMenu(self.menuBar)
        self.menuEDit.setEnabled(True)
        self.menuEDit.setObjectName("menuEDit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionKit_Table = QtWidgets.QAction(MainWindow)
        self.actionKit_Table.setObjectName("actionKit_Table")
        self.actionPictures = QtWidgets.QAction(MainWindow)
        self.actionPictures.setObjectName("actionPictures")
        self.actionSelect_New_Kit = QtWidgets.QAction(MainWindow)
        self.actionSelect_New_Kit.setObjectName("actionSelect_New_Kit")
        self.actionUpdate_Kit_Queue = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Kit_Queue.setObjectName("actionUpdate_Kit_Queue")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout_DDPak = QtWidgets.QAction(MainWindow)
        self.actionAbout_DDPak.setObjectName("actionAbout_DDPak")
        self.actionEdit_Users = QtWidgets.QAction(MainWindow)
        self.actionEdit_Users.setObjectName("actionEdit_Users")
        self.actionAdd_Kit_to_Queue = QtWidgets.QAction(MainWindow)
        self.actionAdd_Kit_to_Queue.setObjectName("actionAdd_Kit_to_Queue")
        self.actionAdd_Kit_to_Queue_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_Kit_to_Queue_2.setObjectName("actionAdd_Kit_to_Queue_2")
        self.actionLogout_2 = QtWidgets.QAction(MainWindow)
        self.actionLogout_2.setObjectName("actionLogout_2")
        self.actionProduction_Reporting = QtWidgets.QAction(MainWindow)
        self.actionProduction_Reporting.setObjectName("actionProduction_Reporting")
        self.actionImport_Fixed_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Fixed_Data.setObjectName("actionImport_Fixed_Data")
        self.actionExport_Fixed_Data = QtWidgets.QAction(MainWindow)
        self.actionExport_Fixed_Data.setObjectName("actionExport_Fixed_Data")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.menuFile.addAction(self.actionExit)
        self.menuEDit.addAction(self.actionKit_Table)
        self.menuEDit.addAction(self.actionPreferences)
        self.menuEDit.addAction(self.actionEdit_Users)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout_DDPak)
        self.menuTools.addAction(self.actionProduction_Reporting)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEDit.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Pak", None))
        self.label_7.setText(QtCore.QCoreApplication.translate("MainWindow", "Pak", None))
        self.label_18.setText(QtCore.QCoreApplication.translate("MainWindow", "Logged in User:", None))
        self.label_3.setText(QtCore.QCoreApplication.translate("MainWindow", "Item Id:", None))
        self.label_4.setText(QtCore.QCoreApplication.translate("MainWindow", "Description:", None))
        self.label_5.setText(QtCore.QCoreApplication.translate("MainWindow", "Net Weight:", None))
        self.label_16.setText(QtCore.QCoreApplication.translate("MainWindow", "Weight Tolerance:", None))
        self.label_6.setText(QtCore.QCoreApplication.translate("MainWindow", "Box:", None))
        self.label_21.setText(QtCore.QCoreApplication.translate("MainWindow", "No. of Kits Packed Today:", None))
        self.label_24.setText(QtCore.QCoreApplication.translate("MainWindow", "Kits on Carriers", None))
        self.radioButton.setText(QtCore.QCoreApplication.translate("MainWindow", "MountsMES", None))
        self.radioButton_2.setText(QtCore.QCoreApplication.translate("MainWindow", "Manual Entry", None))
        self.pushButton_8.setText(QtCore.QCoreApplication.translate("MainWindow", "Select", None))
        self.pushButton_7.setText(QtCore.QCoreApplication.translate("MainWindow", "Add", None))
        self.label_23.setText(QtCore.QCoreApplication.translate("MainWindow", "Messages:", None))
        self.label_8.setText(QtCore.QCoreApplication.translate("MainWindow", "Weight", None))
        self.label_10.setText(QtCore.QCoreApplication.translate("MainWindow", "0", None))
        self.highlabel.setText(QtCore.QCoreApplication.translate("MainWindow", "Over", None))
        self.goodlabel.setText(QtCore.QCoreApplication.translate("MainWindow", "Good", None))
        self.lowlabel.setText(QtCore.QCoreApplication.translate("MainWindow", "Under", None))
        self.label_9.setText(QtCore.QCoreApplication.translate("MainWindow", "Tare:", None))
        self.pushButton.setText(QtCore.QCoreApplication.translate("MainWindow", "Set Tare (F3)", None))
        self.pushButton_3.setText(QtCore.QCoreApplication.translate("MainWindow", "Zero Scale (F4)", None))
        self.pushButton_2.setText(QtCore.QCoreApplication.translate("MainWindow", "Print Label (F1)", None))
        self.pushButton_4.setText(QtCore.QCoreApplication.translate("MainWindow", "Take Picture (F2)", None))
        self.pushButton_6.setText(QtCore.QCoreApplication.translate("MainWindow", "Reprint Label (F5)", None))
        self.label.setText(QtCore.QCoreApplication.translate("MainWindow", "Labels Printed", None))
        self.pushButton_5.setText(QtCore.QCoreApplication.translate("MainWindow", "Delete Selected Label", None))
        self.pushButton_9.setText(QtCore.QCoreApplication.translate("MainWindow", "First", None))
        self.pushButton_10.setText(QtCore.QCoreApplication.translate("MainWindow", "Prev", None))
        self.pushButton_11.setText(QtCore.QCoreApplication.translate("MainWindow", "Next", None))
        self.pushButton_12.setText(QtCore.QCoreApplication.translate("MainWindow", "Last", None))
        self.menuFile.setTitle(QtCore.QCoreApplication.translate("MainWindow", "File", None))
        self.menuEDit.setTitle(QtCore.QCoreApplication.translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(QtCore.QCoreApplication.translate("MainWindow", "Help", None))
        self.menuTools.setTitle(QtCore.QCoreApplication.translate("MainWindow", "Tools", None))
        self.actionExit.setText(QtCore.QCoreApplication.translate("MainWindow", "Exit", None))
        self.actionKit_Table.setText(QtCore.QCoreApplication.translate("MainWindow", "Kit Table", None))
        self.actionPictures.setText(QtCore.QCoreApplication.translate("MainWindow", "Pictures", None))
        self.actionSelect_New_Kit.setText(QtCore.QCoreApplication.translate("MainWindow", "Select New Kit", None))
        self.actionUpdate_Kit_Queue.setText(QtCore.QCoreApplication.translate("MainWindow", "Kit Queue", None))
        self.actionPreferences.setText(QtCore.QCoreApplication.translate("MainWindow", "Preferences", None))
        self.actionAbout_DDPak.setText(QtCore.QCoreApplication.translate("MainWindow", "About DDPak", None))
        self.actionEdit_Users.setText(QtCore.QCoreApplication.translate("MainWindow", "Users", None))
        self.actionAdd_Kit_to_Queue.setText(QtCore.QCoreApplication.translate("MainWindow", "Add Kit to Queue", None))
        self.actionAdd_Kit_to_Queue_2.setText(QtCore.QCoreApplication.translate("MainWindow", "Add Kit to Queue", None))
        self.actionLogout_2.setText(QtCore.QCoreApplication.translate("MainWindow", "Logout", None))
        self.actionProduction_Reporting.setText(QtCore.QCoreApplication.translate("MainWindow", "Production Reporting", None))
        self.actionImport_Fixed_Data.setText(QtCore.QCoreApplication.translate("MainWindow", "Import Fixed Data", None))
        self.actionExport_Fixed_Data.setText(QtCore.QCoreApplication.translate("MainWindow", "Export Fixed Data", None))
        self.actionManual.setText(QtCore.QCoreApplication.translate("MainWindow", "Manual", None))

from PyQt5 import QAxContainer
import myrc_rc

